### ISSUE TITLE
[Android] Every FCM message makes a notification.

### ISSUE THREAD

**Issue by festinalente91** [Vinylize/Yetta-App#122]
There are too many notifications on the android app.
I cannot sleep, please help.
I'm not sure but seems like there are some ways to solve this problem.
[http://stackoverflow.com/a/39782954/4437355](http://stackoverflow.com/a/39782954/4437355)

![fcm_message_stack](https://cloud.githubusercontent.com/assets/8946248/25790713/fce907e6-33f5-11e7-8d87-f077cdf2469b.jpeg)

**Comment by lyw0149** [comment]
죄송합니다. 빠른시일내에 Fix버전으로 업데이트 하도록 하겠습니다.
